/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include "stm32f7xx_hal.h"
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <unistd.h>   // ✅ STDIN/OUT/ERR 매크로

/* UART 핸들: usart.h 없이 외부 선언 */
extern UART_HandleTypeDef huart3;

/* 환경변수 모형 */
char *__env[1] = { 0 };
char **environ = __env;

/* 선택: 세미호스트용 (사용 안함) */
void initialise_monitor_handles(void) {}

/* 기본 syscall들 */
int _getpid(void) { return 1; }
int _kill(int pid, int sig) { (void)pid; (void)sig; errno = EINVAL; return -1; }
void _exit (int status) { _kill(status, -1); while (1) {} }

/* ✅ 표준 출력/오류를 UART3로 연결 */
int _write(int file, char *ptr, int len)
{
    if (file == STDOUT_FILENO || file == STDERR_FILENO)
    {
        // USART3 핸들러가 아직 준비 안 된 경우 → 그냥 무시
        if (huart3.Instance == NULL) return len;

        HAL_UART_Transmit(&huart3, (uint8_t*)ptr, (uint16_t)len, HAL_MAX_DELAY);
        return len;
    }
    errno = EBADF;
    return -1;
}

/* (선택) 표준 입력을 UART3로 연결: 필요 없으면 삭제 가능 */
int _read(int file, char *ptr, int len)
{
    if (file == STDIN_FILENO)
    {
        if (huart3.Instance == NULL)
        {
            errno = EIO;
            return -1;
        }
        /* 한 바이트 블로킹 수신 */
        if (HAL_UART_Receive(&huart3, (uint8_t*)ptr, 1, HAL_MAX_DELAY) == HAL_OK)
            return 1;
        errno = EIO;
        return -1;
    }
    errno = EBADF;
    return -1;
}

int _close(int file) { (void)file; return -1; }
int _fstat(int file, struct stat *st) { (void)file; st->st_mode = S_IFCHR; return 0; }
int _isatty(int file) { (void)file; return 1; }
int _lseek(int file, int ptr, int dir) { (void)file; (void)ptr; (void)dir; return 0; }
int _open(char *path, int flags, ...) { (void)path; (void)flags; return -1; }
int _wait(int *status) { (void)status; errno = ECHILD; return -1; }
int _unlink(char *name) { (void)name; errno = ENOENT; return -1; }
int _times(struct tms *buf) { (void)buf; return -1; }
int _stat(char *file, struct stat *st) { (void)file; st->st_mode = S_IFCHR; return 0; }
int _link(char *old, char *neww) { (void)old; (void)neww; errno = EMLINK; return -1; }
int _fork(void) { errno = EAGAIN; return -1; }
int _execve(char *name, char **argv, char **env) { (void)name; (void)argv; (void)env; errno = ENOMEM; return -1; }
